"""changes in videos

Revision ID: 7c385d5ede5c
Revises: 8a9264eb3fc6
Create Date: 2026-02-04 11:49:29.775452

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7c385d5ede5c'
down_revision: Union[str, Sequence[str], None] = '8a9264eb3fc6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('videos', sa.Column('updated_at', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('videos', 'updated_at')
    # ### end Alembic commands ###
