"""added field to video generation job to track published videos

Revision ID: b19a6c714dfb
Revises: c1f8a30c769e
Create Date: 2026-02-11 23:08:03.259777

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'b19a6c714dfb'
down_revision: Union[str, Sequence[str], None] = 'c1f8a30c769e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('video_generation_jobs', sa.Column('published_video_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_video_generation_jobs_published_video_id'), 'video_generation_jobs', ['published_video_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_video_generation_jobs_published_video_id'), table_name='video_generation_jobs')
    op.drop_column('video_generation_jobs', 'published_video_id')
    # ### end Alembic commands ###
