"""fixes in video model

Revision ID: c1f8a30c769e
Revises: 9d9b02df3acc
Create Date: 2026-02-10 16:21:16.406012

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'c1f8a30c769e'
down_revision: Union[str, Sequence[str], None] = '9d9b02df3acc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('videos', sa.Column('caption', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.drop_column('videos', 'title')
    op.drop_column('videos', 'description')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('videos', sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('videos', sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('videos', 'caption')
    # ### end Alembic commands ###
