"""changes

Revision ID: dcffa0cb959e
Revises: 2a9b20fb836d
Create Date: 2026-02-04 17:14:55.822510

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dcffa0cb959e'
down_revision: Union[str, Sequence[str], None] = '2a9b20fb836d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('videos', sa.Column('likes_count', sa.Integer(), nullable=True))
    op.add_column('videos', sa.Column('comments_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('videos', 'comments_count')
    op.drop_column('videos', 'likes_count')
    # ### end Alembic commands ###
